#!/bin/bash
echo "NEXT_PUBLIC_API_USER_URL=$NEXT_PUBLIC_API_USER_URL" >> .env
echo "NEXT_PUBLIC_API_REQUEST_URL=$NEXT_PUBLIC_API_REQUEST_URL" >> .env
echo "NEXT_PUBLIC_API_REPORT_URL=$NEXT_PUBLIC_API_REPORT_URL" >> .env
echo "AUTH_SECRET=$AUTH_SECRET" >> .env
echo "AUTH_TRUST_HOST=$AUTH_TRUST_HOST" >> .env
